name: Deploy Site
on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.101'
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - run: dotnet run -- deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
