name: Deploy Site
on:
  push:
    branches:
    - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '6.0.101'
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build static site
      run: dotnet run
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./output

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
